export const EXCHANGE_ACTIONS = {
  GET_CRYPTO_PRICE: 'GET_CRYPTO_PRICE',
  GET_CRYPTO_PRICE_SUCCESS: 'GET_CRYPTO_PRICE_SUCCESS',
  GET_CRYPTO_PRICE_FAILED: 'GET_CRYPTO_PRICE_FAILED',

  CREATE_CC_ORDER: 'CREATE_CC_ORDER',
  CREATE_CC_ORDER_SUCCESS: 'CREATE_CC_ORDER_SUCCESS',
  CREATE_CC_ORDER_FAILED: 'CREATE_CC_ORDER_FAILED',
};

import { HANDSHAKE_API } from '@/config';
import { createAPI } from '@/reducers/action';

export const getCryptoPrice = createAPI({
  API: HANDSHAKE_API.EXCHANGE.GET_CRYPTO_PRICE,
  INIT: EXCHANGE_ACTIONS.GET_CRYPTO_PRICE,
  SUCCESS: EXCHANGE_ACTIONS.GET_CRYPTO_PRICE_SUCCESS,
  FAILED: EXCHANGE_ACTIONS.GET_CRYPTO_PRICE_FAILED
});

export const createCCOrder = createAPI({
  API: HANDSHAKE_API.EXCHANGE.CREATE_CC_ORDER,
  INIT: EXCHANGE_ACTIONS.CREATE_CC_ORDER,
  SUCCESS: EXCHANGE_ACTIONS.CREATE_CC_ORDER_SUCCESS,
  FAILED: EXCHANGE_ACTIONS.CREATE_CC_ORDER_FAILED
});
