export default {
  HELLO: 'hello {name}',
  buy: 'Buy',
  sell: 'Sell',
  amount: 'Amount',
  askUsingCreditCard: 'for {fiatCurrency}{total} using a credit card?',
  change: 'Change',
  ccNumber: 'Number',
  ccExpire: 'Expire',
  ccCVC: 'CVV',

  required: 'Required',
  ccExpireTemplate: 'MM/YY',
  securityCode: 'Security Code',
  shakeNow: 'Shake Now',
  offerHandShakeContent: '{offerType} {amount} {currency} for {currency_symbol}{total} in {payment_method}',
  offerDistanceContent: '{distanceMeters} meters ({distanceMiles} miles) away',
  transactonOfferInfo: 'Successful ({success}) / Failed ({failed})',
  createOfferConfirm: 'You are about to {type} {amount} {currency} for {currency_symbol}{total}',
  handshakeOfferConfirm: 'You are about to {type} {amount} {currency} for {currency_symbol}{total}',
  rejectOfferConfirm: 'Do you want to Reject this handshake? You will not be able to make transactions for 4 hours.',
  completeOfferConfirm: 'Do you want to Complete this handshake?',
  withdrawOfferConfirm: 'Do you want to Withdraw this handshake?',
  cancelOfferConfirm: 'Do you want to Cancel this handshake?',
  createOfferSuccessMessage: 'Create offer success',
  shakeOfferSuccessMessage: 'Shake offer success',
  closeOfferSuccessMessage: 'Close offer success',
  completeShakedfferSuccessMessage: 'Complete shaked offer success',
  cancelShakedfferSuccessMessage: 'Cancel shaked offer success',
  withdrawShakedfferSuccessMessage: 'Withdraw shaked offer success',
  buyUsingCreditCardSuccessMessge: 'Buy using Credit Card success',
  notEnoughCoinInWallet: 'You only have {amount}({currency}) in default wallet {currency}. Please add more',
};
