export default {
  HELLO: 'hello {name}',
  buy: 'Buy',
  sell: 'Sell',
  amount: 'amount',
  askUsingCreditCard: 'for {total} {fiatCurrency} using card?',
  change: 'Change',
  ccNumber: 'Number',
  ccExpire: 'Expiry',
  ccCVC: 'CVC',
  overCCLimit: 'You have reached your credit card limit! You have already used {currency}{amount} in the dojo today. ',

  required: 'Required',
  ccExpireTemplate: 'MM/YY',
  securityCode: '325',
  shakeNow: 'Shake',
  offerHandShakeContent: '{offerType} {amount} {currency} for {total} {currency_symbol} in {payment_method}?',
  offerHandShakeContentMe: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMe: '{offerType} {something} for {amount} {currency}',
  offerHandShakeContentMeDone: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMeDone: '{offerType} {something} for {amount} {currency}',
  instantOfferHandShakeContent: 'You{just}{offerType} {amount} {currency} for {total} {currency_symbol} on your card - fee {fee}%',
  offerDistanceContent: '{distance} away',
  transactonOfferInfo: 'Successful ({success}) / Failed ({failed})',
  createOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  handshakeOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  rejectOfferConfirm: 'Do you want to Reject this handshake? You will not be able to make transactions for 4 hours.',
  completeOfferConfirm: 'Finish shaking?',
  withdrawOfferConfirm: 'Are you sure you want to withdraw?',
  cancelOfferConfirm: 'Cancel this order?',
  closeOfferConfirm: 'Finish your order?',
  acceptOfferConfirm: 'Accept the order?',
  createOfferSuccessMessage: 'Success! You have created an offer on Ninja.',
  shakeOfferSuccessMessage: 'Success! A ninja has shaked on your order.',
  closeOfferSuccessMessage: 'Success! Your order is now closed.',
  completeShakedfferSuccessMessage: 'You have successfully shaked on Ninja',
  cancelShakedfferSuccessMessage: 'You have cancelled your order ',
  withdrawShakedfferSuccessMessage: 'Your offer has been withdrawn.',
  buyUsingCreditCardSuccessMessge: 'Your order using your credit card has gone through.',
  notEnoughCoinInWallet: 'You don\'t have enough coin right now. Please top up your wallet.',

  createOfferStoreConfirm: 'Do you want to set up an offer to {intentMsg}?',
  notEnoughCoinInWalletStores: 'You don\'t have enough coin right now. Please top up your wallet.',
  addOfferItemSuccessMassage: 'Success! Your order is now listed on Ninja',
  deleteOfferItemSuccessMassage: 'You have successfully deleted your order.',
  shakeOfferItemSuccessMassage: 'You have successfully shaked on Ninja',
  acceptOfferItemSuccessMassage: 'Good news! Your order has been accepted.',
  cancelOfferItemSuccessMassage: 'Your order has been cancelled!',
  rejectOfferItemSuccessMassage: 'You rejected a fellow ninja\'s order.',
  completeOfferItemSuccessMassage: 'Good news! Your order has been completed.',
  offerStoresAlreadyCreated: 'Oops! You already created an order on Ninja.',
  offerStoreHandShakeContent: '{offerTypeBuy} {amountBuy} {currency} at {fiatAmountBuy} {fiatAmountCurrency}. {offerTypeSell} {amountSell} {currency} at {fiatAmountSell} {fiatAmountCurrency}',
  requireDefaultWalletOnMainNet: 'You must set your wallet on Mainnet',
  movingCoinToEscrow: 'Moving your coin to escrow. This may take a few minutes.',
  movingCoinFromEscrow: 'Moving your coin from escrow. This may take a few minutes.',
  'ex.create.label.amountBuy': 'I want to buy',
  'ex.create.label.amountSell': 'I want to sell',
  'ex.create.label.marketPrice': 'Current market price',
  'ex.create.label.premiumBuy': 'My price',
  'ex.create.label.premiumSell': 'My price',
  'ex.create.label.premiumSellExplanation': 'Market price ± percentage',
  'ex.create.label.nameStation': 'Station name',
  'ex.create.label.phone': 'Phone',
  'ex.create.label.address': 'Meet-up place',
  'ex.create.label.beASeller': 'Be a seller',
  'ex.create.label.beABuyer': 'You can also be a buyer',
  'ex.create.label.stationInfo': 'Station information',

  'ex.createLocal.label.iWantTo': 'I want to',
  'ex.createLocal.placeholder.anyItem': 'any item or service',
  'ex.createLocal.label.coin': 'Coin',
  'ex.createLocal.label.amount': 'Amount',
  'ex.createLocal.label.phone': 'Phone',
  'ex.createLocal.label.address': 'Meet-up place',

  'ex.discover.label.priceBuy': 'BUY',
  'ex.discover.label.priceSell': 'SELL',
  'ex.discover.label.reviews': '({reviewCount})',
  'ex.discover.banner.text': 'Got coins? Turn them into a money-making machine.',
  'ex.discover.banner.btnText': 'BECOME A LOCAL EXCHANGE',
  'ex.discover.shakeDetail.label.amount': 'Amount',
  'ex.discover.shakeDetail.label.total': 'Total',
  'ex.discover.shakeDetail.label.maximum': 'Maximum:',
  'ex.me.label.with': 'With',
  'ex.me.label.from': 'From',
  'ex.me.label.about': 'About',
  'ex.btn.confirm': 'Confirm',
  'ex.btn.OK': 'OK',
  'ex.btn.notNow': 'Not now',

  'ex.label.buy': 'Buy',
  'ex.label.sell': 'Sell',
  'ex.label.bought': 'Bought',
  'ex.label.sold': 'Sold',
  'ex.label.buying': 'Buying',
  'ex.label.selling': 'Selling',
  'ex.label.buyer': 'buyer',
  'ex.label.seller': 'seller',

  'ex.exchange.status.created': 'created',
  'ex.exchange.status.active': 'active',
  'ex.exchange.status.closing': 'closing',
  'ex.exchange.status.closed': 'closed',
  'ex.exchange.status.shaking': 'shaking',
  'ex.exchange.status.shake': 'shake',
  'ex.exchange.status.completing': 'completing',
  'ex.exchange.status.completed': 'completed',
  'ex.exchange.status.withdrawing': 'withdrawing',
  'ex.exchange.status.withdraw': 'withdraw',
  'ex.exchange.status.rejecting': 'rejecting',
  'ex.exchange.status.rejected': 'rejected',

  'ex.cc.status.processing': 'Processing',
  'ex.cc.status.success': 'Done',
  'ex.cc.status.cancelled': 'Failed',

  'ex.shop.status.created': 'Verifying...',
  'ex.shop.status.active': 'Active',
  'ex.shop.status.closing': 'Pending...',
  'ex.shop.status.closed': 'Closed',

  'ex.shop.shake.status.pre_shaking': 'Shake pending',
  'ex.shop.shake.status.pre_shake': 'Shook',
  'ex.shop.shake.status.shaking': 'Shake pending...',
  'ex.shop.shake.status.shake': 'Shook',
  'ex.shop.shake.status.rejecting': 'Rejecting',
  'ex.shop.shake.status.rejected': 'Rejected',
  'ex.shop.shake.status.completing': 'Completing...',
  'ex.shop.shake.status.completed': 'Done',
  'ex.shop.shake.status.cancelling': 'Cancelling',
  'ex.shop.shake.status.cancelled': 'Cancelled',

  'ex.error.systemError': 'Sorry Ninja. Something went wrong. Come back soon.',
  'ex.error.312': 'Oh no! You cancelled your offer. You will not be able to make orders for 4 hours. Sorry',
  'ex.error.313': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.314': 'Looks like that listing has been deleted.',
  'ex.error.315': 'Sorry ninja, someone else got there first.',
  'ex.error.1': 'Oops! Something went wrong. Come back soon.',
  'ex.error.3': 'It looks like that token is invalid.',
  'ex.error.301': 'You are already a ninja.',
  'ex.error.302': 'Sorry, that ninja does not exist.',
  'ex.error.303': 'It looks like you have reached your credit card limit.',
  'ex.error.309': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.default': 'Oops! Something went wrong.',

  'error.required': 'Required',
  'error.requiredOne': 'You need to fill in one of these!',
  'error.greaterThan': 'Must be greater than {min}',
  'error.lessThan': 'Must be less than {max}',

  'btn.initiate': 'Initiate',
  'btn.shake': 'Shake',
  'btn.reject': 'Reject',
  'btn.complete': 'Complete',
  'btn.withdraw': 'Withdraw',
  'btn.cancel': 'Cancel',
  'btn.close': 'Close',
  'btn.accept': 'Accept',

  // FAQ
  FAQ_TITLE: 'FAQ',
  FAQ_HEADER_YELLOW: '',
  FAQ_HEADER: '予測 Exchange を分散',
  FAQ_DATA: [
    {
      question: '忍者 PEX ってなに?',
      answer: '忍者は、Ethereum blockchain 上で実行される匿名のピア ツー ピア分散予測交換です。',
    },
    {
      question: 'PEX について特別なは?なぜ私は 1 つに賭ける必要があります?',
      answer: '中央官庁やブック メーカーを経由せず直接賭ける互いに当事者をことができます。これは 100% 匿名、兆候ダウンロードが必要になりません。賭け金の管理や賞金の決済によって実行されますまとめて blockchain のネットワークは、すべての単一点障害からユーザーを保護します。独自の予測市場を作成することも。',
    },
    {
      question: 'エーテルは必要ですか。それが他の cryptocurrencies を支えるか。',
      answer: 'うん。忍者はのみ今のところ、ETH を受け付けますが、他の通貨のサポートが非常にすぐに追加されます。',
    },
    {
      question: '忍者の始まる.',
      isList: true,
      answer: [
        {
          title: 'エーテルを得る。',
          content: 'あなたのクレジット カードまたは Coinbase または Binance のような人気のあるコインの交換から直接 PEX の ETH を購入できますか。',
        },
        {
          title: 'PEX 財布をトップします。',
          content: 'PEX 財布に ETH を転送します。PEX の財布は完全に分散、あなたの携帯電話に秘密キーを保管、あなただけ転送、ETH を送受信することができます。',
        },
        {
          title: 'ベットを配置します。',
          content: 'ピックするベット (すなわちブラジル - スペイン)、結果 (すなわちブラジル wins) とサイト (サポートまたは結果に対して賭け) 市場\n' +
          'ベット (すなわち 1 ETH) とオッズの場合出資を入力 (つまり 1/2.25\n' +
          'BEX マッチング エンジンは、ベットを設定する予想に反して別の順序を見つけます。',
        },
        {
          title: 'レポートを待つ:',
          content: 'あなたのアカウントに、エスクロー スマート契約からはあなたの賞金自動的に転送されますあなたが勝った場合。',
        },
      ],
    },
    {
      question: '私は自分の最寄りののオッズを設定できますか。どのようにですか?',
      answer: 'うん！自分の賭けを作成するには、興味を持っているイベントとの賭けを結果を入力します。その後、単にあなたの株式と場合のオッズを入力します。[PEX エンジン自動的に検索し、誰もが同じイベントに興味を持っている、あなたの勝算を受け入れる人を一致させます。',
    },
    {
      question: 'どのように不快な/違法賭けを警察か。',
      answer: '我々 は現在と道場で不適切な行動をフラグする均衡のシステムを構築しています。',
    },
    {
      question: 'システムは、どのように人々 の間の賭の結果を知っていますか人は仲裁人として機能し、別契約の締結での対 1 つの結果を確認しますか。',
      answer: '忍者はすぐ結果を確認して病名告知 (記者の DAO!) の報奨のため完全に分散型ソリューションがあります。一方で、FIFA ワールド カップのための時間だけで、起動すると、我々 のチームがパブリック ソース (livescore.com) を使用、記者を務めます。',
    },
    {
      question: 'コインははどこで開催されますか。',
      answer: '誰が資金を保持しています。すべての資金は、解像度に達するまで条件付け捺印証書安全な保存されます。',
    },
    {
      question: '従来の方法を使用する代わりに blockchain に賭けるなぜとする必要がありますか。',
      answer: '分散予測交換は誰とでも直接、独自のオッズと賭けを作成するための自由は 100% 忍者の匿名性を提供し、支払いを保証を提供します。',
    },
    {
      question: '方法についてプライバシーと匿名性ですか。',
      answer: '忍者には、ダウンロード不要とないサインアップが必要です。つまり、パスワード、電話番号がなく、メールを送信しません。100% 年の匿名。',
    },
    {
      question: '料金を支払う必要がありますか。',
      answer: '手数料の 2 つの主なタイプがある: (ベットを作成する忍者) の作成者料とネットワーク料 (プラットフォームを維持することの方に行くされる創作者手数料の割合)。',
    },
    {
      question: 'どのような結果を確定するしたいですか。',
      answer: '何もない。あなたが勝った場合、あなたの賞金はあなたのアカウントに自動的に転送されます。紛失した場合、それは誰か他の人のアカウントになります。',
    },
    {
      question: 'どこに賭ける一致を検索できますか。',
      answer: 'ホームページにおいて、継続的なベットと市場を参照することができます。あなたのように見つけることができない場合は、あなた自身を作成!',
    },
    {
      question: '他のスポーツよりも、私は他の何かに賭けることができるか。どのように動作するのか。',
      answer: '非常に早く、忍者は、太陽の下ですべてに適用されます。唯一の制限はあなたの創造性になります。簡単に任意の将来のイベントを任意の市場を作成できます、スポーツのこと、政治、科学、市場、気候. ',
    },
    {
      question: 'はハンドシェイクのモバイル アプリに起こるつもりですか。',
      answer: '我々 は忍者携帯サイトにハンドシェイク (と約束、IOUs、契約アップロード等のようなあなたのお気に入りの機能) を統合するでしょう。',
    },
  ],

  // MobileOrTablet components
  MOT_TITLE: '何か匿名の交流',
  MOT_CONTENT_0: '忍者ネットワークのみアクセス可能です携帯電話を介して',
  MOT_CONTENT_1: '匿名エントリを得るためにあなたの携帯電話のブラウザーで',
  MOT_CONTENT_2: 'を開きます。',
  MOT_CONTENT_3: 'ダウンロードは必要ありません。サインアップは必要ありません。',
  MOT_LIST_CONTENT: [
    {
      mainContent: '',
      placeHolderLink: 'ホワイト ペーパー',
      link: 'https://medium.com/@ninjadotorg/shakeninja-bex-1c938f18b3e8',
      mainContent1: 'を読む',
      isBlankTarget: true,
    },
    {
      mainContent: 'あなたの',
      placeHolderLink: '質問',
      mainContent1: 'にお答え',
      link: '/faq',
    },
    {
      mainContent: '',
      placeHolderLink: '電報',
      mainContent1: 'の道場に参加します。',
      link: 'https://t.me/ninja_org',
      isBlankTarget: true,
    },
  ],

  /*
  *
  * White Paper
  *
  * ******************************************************************************************* */
  WHITE_PAPER_H1: 'Ethereum 匿名のピア ツー ピア予測交換',
  WHITE_PAPER_SUBTITLE_1: 'こんにちは！Roc、バクナワ、Hakawai、グローツラング忍者チームからです。我々 は、blockchain の電子予測交換を構築しています。ここでは私たちがなぜ、それとどのように動作!',
  WHITE_PAPER_SUBTITLE_2: '会話に参加',
  WHITE_PAPER_INTRO: '導入',
  WHITE_PAPER_INTRO_1: 'オンライン賭博は、信頼できる第三者としてブック メーカーによってほとんど専ら実行されます。場合は通常、ユーザーは、この「一元的な信頼できる 30 パーティー問題」によって苦しみます。',
  WHITE_PAPER_INTRO_2: [
    'ブック メーカー (彼らは常に勝つ) それらを好む常にオッズを設定します。',
    'ブック メーカーは、高額の 5% をお楽しみください。 - すべての賭の 30% のマージン',
    'ベットは可逆的で、賞金があります。',
    '完全に匿名性は不可能',
    '詐欺はやむを得ないと受け入れたそうであります。',
    '単一障害点 - ブック メーカーが消える場合はどうですか?',
    '賭けるギャンブルと見なされます - 主に一元的なパーティーのため、過度に危険な\'の透明性の欠如',
  ],
  WHITE_PAPER_INTRO_3: 'これらの問題は、ユーザーが 2 つの悪のうち小さい方益々 不思議ですのでオフラインで賭けになるときに 10 を掛けます。',
  WHITE_PAPER_INTRO_4_HIGH_LIGHT: 'ソリューション: 消極的信頼をどこからでも任意の 2 つの匿名の政党を許可する暗号化の証明書に置き換えます電子予測システムにお互い信頼できる第三者機関を必要とせず直接賭ける世界で。',
  WHITE_PAPER_INTRO_5: '匿名ピア ツー ピア電子予測交換 (PEX) により、中央官庁やブック メーカーを経由せず直接賭ける互いに当事者。賭け金の管理や賞金の決済によって実行されますまとめて blockchain のネットワークは、すべての単一点障害からユーザーを保護します。PEX には、エキサイティングなユース ケース、以前任意の伝統的な賭けのメカニズムの下で不可能なことができるユニークなプロパティがあります。',
  WHITE_PAPER_INTRO_6: 'それは私たちの希望は、PEX が賭けの今日の知覚が変更されます。 - しばしば不必要として描かれている怪しげなギャンブル ゲーム原因主に一元的な当事者の利益を作ることの非倫理的な競争の激しい方法を探しているに依存します。',
  WHITE_PAPER_INTRO_7_HIGH_LIGHT: 'オープンで透明な予測市場交換と謎に包まれたギャンブル業界に直接挑戦する PEX 。',
  WHITE_PAPER_INTRO_8: 'この交換が人が集まるし、彼らはいつもスポーツ、政治、科学、市場、気候と太陽の下ですべての将来のイベントに、行っているようを予測 - 人は世界に投資している個人として当然のことを築いています',
  WHITE_PAPER_PEX: 'PEX とは何ですか。',
  WHITE_PAPER_PEX_1: 'PEX は、誰もが簡単な方法を提供する匿名のピア ツー ピア分散予測交換 Ethereum blockchain 上で実行されます。',
  WHITE_PAPER_PEX_2: [
    '結果注文サポート(Ask) またはに対して注文(入札) を配置します。',
    '(オッズを置く)マーケットメーカーや市場係(オッズの背部)',
    '自分の予測市場の創造であります。',
    '賞金を受け取る即座に (スマート契約保証)',
  ],
  WHITE_PAPER_PEX_3: 'ベットを配置します。',
  WHITE_PAPER_OUTCOME: '取引可能な資産としての成果。価格としてオッズ。',
  WHITE_PAPER_OUTCOME_1: '証券取引所で取引可能資産は共有をとトレーダーは株価の単位(例えば販売 100 アップルの株式で 200 ドル) に賭けます',
  WHITE_PAPER_OUTCOME_2: 'カテゴリーが選択できます資産は、コインの交換、コインとトレーダーは賭けたコイン単価(例えば 2 Bitcoin 7000 ドルを購入する)。',
  WHITE_PAPER_OUTCOME_3: 'Similarly, in a decentralized prediction exchange like PEX, the tradeable asset is outcome of an event, and traders bet on the odds of that outcome. They can bet for the outcome (support it), or bet against it. For example: an outcome of the match Brazil vs. Spain could be that “Brazil wins”. John can bet on that outcome with odds of 2.0. Mary can bet on that outcome with odds of 2.25. Peter can bet against that outcome (“Brazil loses” or “Brazil draws”) with odds of 1.9.',
  WHITE_PAPER_OUTCOME_4: 'A different type of exchange.',
  WHITE_PAPER_COMPARE: 'PEX vs. Traditional betting',
  WHITE_PAPER_COMPARE_1: 'Importantly, PEX does not accept bets and hold stakes, but instead matches the users who support the outcome with the users who are against the outcome. The stakes are held in an Escrow smart contract.',
  WHITE_PAPER_COMPARE_2: 'The Escrow smart contract is unstoppable. It runs exactly as programmed — to forward its escrow balance to the winner at the end — without any possibility of downtime, fraud or third-party interference. Once both parties commit to a bet, it is irreversible. Payment is guaranteed and instant.',
  WHITE_PAPER_COMPARE_3: 'The entire process happens without any party revealing their identities. It’s 100% anonymous.',
  WHITE_PAPER_COMPARE_4: 'All this happens without a central authority or bookmaker. It’s carried out collectively by all the nodes of the blockchain.',
  WHITE_PAPER_COMPARE_5: 'This is why you should bet on the blockchain.',
  WHITE_PAPER_PEX_WORK: 'How does PEX work?',
  WHITE_PAPER_PEX_WORK_SUB_TITLE: 'PEX is different from what you know. It also provides more autonomy than what you know. Just as importantly, it is designed to be easy to create bet markets and place bet orders.',
  WHITE_PAPER_STEP_1: 'Step 1: Get Ether',
  WHITE_PAPER_STEP_1_1: 'If you don’t have ETH yet, you have a choice of buying ETH directly in PEX with your credit card. You can also buy ETH from popular coin exchanges like Coinbase or Binance.',
  WHITE_PAPER_STEP_1_2: 'PEX will support other cryptocurrencies soon.',
  WHITE_PAPER_STEP_1_3: 'Easily buy ETH in-app.',
  WHITE_PAPER_STEP_2: 'Step 2: Top up your PEX Wallet',
  WHITE_PAPER_STEP_2_1: 'Transfer the ETH you just bought into the PEX Wallet, so that you can start placing bets with your ETH. The PEX Wallet is completely decentralized. The private key is held on your phone and only you can access it. Only you can transfer and receive ETH.',
  WHITE_PAPER_STEP_2_2: 'The neatly organized PEX wallet.',
  WHITE_PAPER_STEP_3: 'Step 3: Place a bet',
  WHITE_PAPER_STEP_3_1: 'First, pick a prediction market that interests you (i.e. Brazil — Spain), the outcome (i.e. “Brazil wins”) and the side (i.e. support or bet against the outcome).',
  WHITE_PAPER_STEP_3_2: 'Then enter the stake you want to bet (i.e. 1 ETH) and the odds (i.e. 1/2.25). The stake will be put into an escrow smart contract. The PEX Matching Engine will then find another order that bets against the odds you set.',
  WHITE_PAPER_STEP_3_3: 'That’s it.',
  WHITE_PAPER_STEP_3_4: 'Our ETH is on Argentina for this one.',
  WHITE_PAPER_STEP_4: 'Step 4: Wait for the report',
  WHITE_PAPER_STEP_4_1: 'Once the event ends, the reporter of the market will report the result within the reporting window (set by the market creator). Generally, you should expect to have the report within minutes. If you win, your winnings will be automatically transferred from the escrow smart contract to your account.',
  WHITE_PAPER_STEP_4_2: 'May the odds be ever in your favour.',
  WHITE_PAPER_CREATE: 'Create your own prediction markets',
  WHITE_PAPER_CREATE_1: 'While most users will place orders in existing markets, PEX allows anyone to create a prediction market about any future event — be it in sports, politics, science, or literally any other aspect of modern life. You, as the market creator, can set the market fee, the market closing time, the reporter of the outcome, and the reporting deadline.',
  WHITE_PAPER_ARCHITECTURE: 'PEX Architecture',
  WHITE_PAPER_ARCHITECTURE_1: 'The core components of the PEX architecture are:',
  WHITE_PAPER_ARCHITECTURE_2_HL: 'Prediction Market',
  WHITE_PAPER_ARCHITECTURE_2: 'PEX allows anyone to create a prediction market about any future event. This can be in any field — sports, politics, science, lifestyle, even weather and so on. The only limit here is your creativity. Each market is part of an on-chain smart contract. It has its own order book, makers and takers.',
  WHITE_PAPER_ARCHITECTURE_3_HL: 'Order Book',
  WHITE_PAPER_ARCHITECTURE_3: 'Each Prediction Market has its own order book. PEX Order Book manages all Support Outcome Orders (ask) and all Against Outcome Order (bid). It aggregates all orders with the same price (odds) into an entry on the order book.',
  WHITE_PAPER_ARCHITECTURE_3_1: 'The order book.',
  WHITE_PAPER_ARCHITECTURE_4_HL: 'Matching Engine',
  WHITE_PAPER_ARCHITECTURE_4_1: 'PEX uses a first-in, first-out (FIFO) order book. Orders are executed in price-time priority. This means that it will match by price first, and if there are two orders with the same price, then it will match by time.',
  WHITE_PAPER_ARCHITECTURE_4_2: 'In some cases, the amount placed on either side is uneven, and the order will be partially filled. The remaining order will be matched with the next best price-then-time in the order book until the order is completely filled.',
  WHITE_PAPER_ARCHITECTURE_4_3: 'Your perfect match.',
  WHITE_PAPER_ARCHITECTURE_4_4: [
    'A user places a Support Outcome Order into the Open Order Book',
    'Another user place an Against Outcome Order into the Open Order Book',
    'Matching Engine finds a match and moves both Orders from the Open Order Book to Matched Order Book',
  ],
  WHITE_PAPER_ARCHITECTURE_5_HL: 'REST API',
  WHITE_PAPER_ARCHITECTURE_5: 'PEX REST API has endpoints for order management, account management, and public market data.',
  WHITE_PAPER_ARCHITECTURE_6_HL: 'Web Socket',
  WHITE_PAPER_ARCHITECTURE_6: 'PEX Web Socket feed provides real-time market data updates for orders and trades.',
  WHITE_PAPER_PRIVACY: 'Privacy & Anonymity',
  WHITE_PAPER_PRIVACY_SUB: 'The privacy afforded to the user is a deliberate design.',
  WHITE_PAPER_PRIVACY_1_HL: 'No downloads',
  WHITE_PAPER_PRIVACY_1: 'PEX is not a mobile app. It’s freely accessible on the mobile web. While native mobile apps sometimes have better UI/UX, they must be hosted by centralized app stores like Android Play Store or Apple App store. In our view, a more attractive UI is not an acceptable tradeoff for compromised privacy.',
  WHITE_PAPER_PRIVACY_2_HL: 'No sign ups',
  WHITE_PAPER_PRIVACY_2_1: 'The need for a password, email or phone number is obsolete.',
  WHITE_PAPER_PRIVACY_2_2: 'PEX doesn’t collect your personal information. You can use PEX with complete privacy. When you first open PEX, a public/private keypair will be created silently in the background and stored locally on your phone. The public key acts as your anonymous username, and the private key is your password. PEX doesn’t have access to your private key — only you do.',
  WHITE_PAPER_PRIVACY_2_3: 'Note that in the Profile Settings, we provide an option for the user to enter their email address. The purpose is not to collect your email, but for a better experience, especially in use cases related to payments. It’s completely optional.',
  WHITE_PAPER_PRIVACY_2_4: 'Note also that there is an option to backup your private key in Settings. We highly recommend doing so.',
  WHITE_PAPER_PRIVACY_3_HL: 'Anonymous prediction',
  WHITE_PAPER_PRIVACY_3: 'PEX is built on top of Ethereum, which is a public blockchain, but privacy is maintained by keeping your public key anonymous. While the public can see that someone is predicting on something, it’s almost impossible to find out who that someone is.',
  WHITE_PAPER_PRIVACY_4_HL: 'Anonymous order matching',
  WHITE_PAPER_PRIVACY_4: 'Similar to stock and coin exchanges, the order book, sizes, odds, and time are public, but the order book doesn’t disclose who the order makers and takers are. The order book records the bet anonymous parties place against each other, based on their opposing predictions of an event. Once the event concludes and the report is available, the escrowed funds are transferred automatically to the winner.',
  WHITE_PAPER_FEE: 'Fees',
  WHITE_PAPER_FEE_1: 'There are two main types of fees: winning fee and network fee.',
  WHITE_PAPER_FEE_2: 'The winning fee is set by the market creator, as a percentage of the total winnings of that market. It’s entirely up to the market creator to set their own fees. Since PEX allows anyone to create a prediction market, we expect that the fees will be very competitive among markets. This is the best case scenario for users.',
  WHITE_PAPER_FEE_3: 'The network fee is 20% of the creator’s winning fee. This pays for engineering, infrastructure, and maintenance of the network. At the beginning, this will be undertaken by the Core Ninja Team. But we expect that over time we will decentralize the team and design a mechanism that opens it up to the entire community.',
  WHITE_PAPER_FEE_4: 'Optionally, we are considering a referral fee for the market creator. The referral pool could be 10% — 20% of the winning fee, which will help in adding a lot more users to the market.',
  WHITE_PAPER_SETTLEMENT: 'Settlement',
  WHITE_PAPER_SETTLEMENT_1: 'The deeper we dive into building PEX, the more it seems that we have to initially strike a compromise between speed and decentralization, while always retaining security. In relation to settlement, which requires the report of the outcome to be available immediately after each event (i.e. a sports event), we will opt for speed, for now.',
  WHITE_PAPER_SETTLEMENT_2: 'In the first release, the Core Ninja Team will assume the reporting role and report the outcome of all events. We’re researching and designing a decentralized mechanism that will allow the community to report the outcomes.',
  WHITE_PAPER_SUMMARY: 'Summary',
  WHITE_PAPER_SUMMARY_1: 'PEX is a purely peer-to-peer version of electronic prediction that allows parties to bet directly against each other without going through a central authority or bookmaker',
  WHITE_PAPER_SUMMARY_2: 'PEX is open-source; its design is public, nobody owns or controls PEX and everyone can take part.',
  WHITE_PAPER_SUMMARY_3: 'PEX is open source at',
  WHITE_PAPER_SUMMARY_4: 'Build PEX with us. Join the conversation at',
  WHITE_PAPER_END: 'And it actually works',
  WHITE_PAPER_END_1: 'Hey, thanks for reading. Ninja will go live on the testnet on 5 June! We’re excited to hear your thoughts.',

};
