export default {
  HELLO: 'hello {name}',
  buy: 'Buy',
  sell: 'Sell',
  amount: 'amount',
  askUsingCreditCard: 'for {total} {fiatCurrency} using card?',
  change: 'Change',
  ccNumber: 'Number',
  ccExpire: 'Expiry',
  ccCVC: 'CVC',
  overCCLimit: 'You have reached your credit card limit! You have already used {currency}{amount} in the dojo today. ',

  required: 'Required',
  ccExpireTemplate: 'MM/YY',
  securityCode: '325',
  shakeNow: 'Shake',
  offerHandShakeContent: '{offerType} {amount} {currency} for {total} {currency_symbol} in {payment_method}?',
  offerHandShakeContentMe: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMe: '{offerType} {something} for {amount} {currency}',
  offerHandShakeContentMeDone: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMeDone: '{offerType} {something} for {amount} {currency}',
  instantOfferHandShakeContent: 'You{just}{offerType} {amount} {currency} for {total} {currency_symbol} on your card - fee {fee}%',
  offerDistanceContent: '{distance} away',
  transactonOfferInfo: 'Successful ({success}) / Failed ({failed})',
  createOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  handshakeOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  rejectOfferConfirm: 'Do you want to Reject this handshake? You will not be able to make transactions for 4 hours.',
  completeOfferConfirm: 'Finish shaking?',
  withdrawOfferConfirm: 'Are you sure you want to withdraw?',
  cancelOfferConfirm: 'Cancel this order?',
  closeOfferConfirm: 'Finish your order?',
  acceptOfferConfirm: 'Accept the order?',
  createOfferSuccessMessage: 'Success! You have created an offer on Ninja.',
  shakeOfferSuccessMessage: 'Success! A ninja has shaked on your order.',
  closeOfferSuccessMessage: 'Success! Your order is now closed.',
  completeShakedfferSuccessMessage: 'You have successfully shaked on Ninja',
  cancelShakedfferSuccessMessage: 'You have cancelled your order ',
  withdrawShakedfferSuccessMessage: 'Your offer has been withdrawn.',
  buyUsingCreditCardSuccessMessge: 'Your order using your credit card has gone through.',
  notEnoughCoinInWallet: 'You don\'t have enough coin right now. Please top up your wallet.',

  createOfferStoreConfirm: 'Do you want to set up an offer to {intentMsg}?',
  notEnoughCoinInWalletStores: 'You don\'t have enough coin right now. Please top up your wallet.',
  addOfferItemSuccessMassage: 'Success! Your order is now listed on Ninja',
  deleteOfferItemSuccessMassage: 'You have successfully deleted your order.',
  shakeOfferItemSuccessMassage: 'You have successfully shaked on Ninja',
  acceptOfferItemSuccessMassage: 'Good news! Your order has been accepted.',
  cancelOfferItemSuccessMassage: 'Your order has been cancelled!',
  rejectOfferItemSuccessMassage: 'You rejected a fellow ninja\'s order.',
  completeOfferItemSuccessMassage: 'Good news! Your order has been completed.',
  offerStoresAlreadyCreated: 'Oops! You already created an order on Ninja.',
  offerStoreHandShakeContentBuy: '{offerTypeBuy} {amountBuy} {currency} at {fiatAmountBuy} {fiatAmountCurrency}. ',
  offerStoreHandShakeContentSell: '{offerTypeSell} {amountSell} {currency} at {fiatAmountSell} {fiatAmountCurrency}.',
  requireDefaultWalletOnMainNet: 'You must set your wallet on Mainnet',
  movingCoinToEscrow: 'Moving your coin to escrow. This may take a few minutes.',
  movingCoinFromEscrow: 'Moving your coin from escrow. This may take a few minutes.',
  'ex.create.label.amountBuy': 'I want to buy',
  'ex.create.label.amountSell': 'I want to sell',
  'ex.create.label.marketPrice': 'Current market price',
  'ex.create.label.premiumBuy': 'My price',
  'ex.create.label.premiumSell': 'My price',
  'ex.create.label.premiumSellExplanation': 'Market price ± percentage',
  'ex.create.label.nameStation': 'Station name',
  'ex.create.label.phone': 'Phone',
  'ex.create.label.address': 'Meet-up place',
  'ex.create.label.beASeller': 'Be a seller',
  'ex.create.label.beABuyer': 'You can also be a buyer',
  'ex.create.label.stationInfo': 'Station information',

  'ex.createLocal.label.iWantTo': 'I want to',
  'ex.createLocal.placeholder.anyItem': 'any item or service',
  'ex.createLocal.label.coin': 'Coin',
  'ex.createLocal.label.amount': 'Amount',
  'ex.createLocal.label.phone': 'Phone',
  'ex.createLocal.label.address': 'Meet-up place',

  'ex.discover.label.priceBuy': 'BUY',
  'ex.discover.label.priceSell': 'SELL',
  'ex.discover.label.reviews': '({reviewCount})',
  'ex.discover.banner.text': 'Got coins? Turn them into a money-making machine.',
  'ex.discover.banner.btnText': 'BECOME A LOCAL EXCHANGE',
  'ex.discover.shakeDetail.label.amount': 'Amount',
  'ex.discover.shakeDetail.label.total': 'Total',
  'ex.discover.shakeDetail.label.maximum': 'Maximum:',
  'ex.me.label.with': 'With',
  'ex.me.label.from': 'From',
  'ex.me.label.about': 'About',
  'ex.btn.confirm': 'Confirm',
  'ex.btn.OK': 'OK',
  'ex.btn.notNow': 'Not now',

  'ex.label.buy': 'Buy',
  'ex.label.sell': 'Sell',
  'ex.label.bought': 'Bought',
  'ex.label.sold': 'Sold',
  'ex.label.buying': 'Buying',
  'ex.label.selling': 'Selling',
  'ex.label.buyer': 'buyer',
  'ex.label.seller': 'seller',

  'ex.exchange.status.created': 'created',
  'ex.exchange.status.active': 'active',
  'ex.exchange.status.closing': 'closing',
  'ex.exchange.status.closed': 'closed',
  'ex.exchange.status.shaking': 'shaking',
  'ex.exchange.status.shake': 'shake',
  'ex.exchange.status.completing': 'completing',
  'ex.exchange.status.completed': 'completed',
  'ex.exchange.status.withdrawing': 'withdrawing',
  'ex.exchange.status.withdraw': 'withdraw',
  'ex.exchange.status.rejecting': 'rejecting',
  'ex.exchange.status.rejected': 'rejected',

  'ex.cc.status.processing': 'Processing',
  'ex.cc.status.success': 'Done',
  'ex.cc.status.cancelled': 'Failed',

  'ex.shop.status.created': 'Verifying...',
  'ex.shop.status.active': 'Active',
  'ex.shop.status.closing': 'Pending...',
  'ex.shop.status.closed': 'Closed',

  'ex.shop.shake.status.pre_shaking': 'Shake pending',
  'ex.shop.shake.status.pre_shake': 'Shook',
  'ex.shop.shake.status.shaking': 'Shake pending...',
  'ex.shop.shake.status.shake': 'Shook',
  'ex.shop.shake.status.rejecting': 'Rejecting',
  'ex.shop.shake.status.rejected': 'Rejected',
  'ex.shop.shake.status.completing': 'Completing...',
  'ex.shop.shake.status.completed': 'Done',
  'ex.shop.shake.status.cancelling': 'Cancelling',
  'ex.shop.shake.status.cancelled': 'Cancelled',

  'ex.error.systemError': 'Sorry Ninja. Something went wrong. Come back soon.',
  'ex.error.312': 'Oh no! You cancelled your offer. You will not be able to make orders for 4 hours. Sorry',
  'ex.error.313': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.314': 'Looks like that listing has been deleted.',
  'ex.error.315': 'Sorry ninja, someone else got there first.',
  'ex.error.1': 'Oops! Something went wrong. Come back soon.',
  'ex.error.3': 'It looks like that token is invalid.',
  'ex.error.301': 'You are already a ninja.',
  'ex.error.302': 'Sorry, that ninja does not exist.',
  'ex.error.303': 'It looks like you have reached your credit card limit.',
  'ex.error.309': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.default': 'Oops! Something went wrong.',

  'error.required': 'Required',
  'error.requiredOne': 'You need to fill in one of these!',
  'error.greaterThan': 'Must be greater than {min}',
  'error.lessThan': 'Must be less than {max}',

  'btn.initiate': 'Initiate',
  'btn.shake': 'Shake',
  'btn.reject': 'Reject',
  'btn.complete': 'Complete',
  'btn.withdraw': 'Withdraw',
  'btn.cancel': 'Cancel',
  'btn.close': 'Close',
  'btn.accept': 'Accept',

  // FAQ
  FAQ_TITLE: '자주 묻는 질문(FAQ)',
  FAQ_HEADER_YELLOW: '',
  FAQ_HEADER: '예측 Exchange 분산',
  FAQ_DATA: [
    {
      question: '닌자 PEX는 무엇입니까? ',
      answer: '닌자는 테리 blockchain 위에 실행 하는 익명 피어-투-피어 분산된 예측 교환. ',
    },
    {
      question: 'PEX에 대 한 특별 한 무엇입니까? 왜 내가 하나 내기를 한다?',
      answer: '당사자를 중앙 기관 또는 도박을 거치지 않고 직접 서로 대 한 내기 수 있습니다. 이것은 100% 익명, 필요 없는 다운로드를 흔적. 베팅의 관리 및 위 닝의 정착은 총칭 의해 수행 실패의 모든 단일 지점에서 사용자를 보호 하는 blockchain 네트워크. 또한 자신의 예측 시장 만들 수 있습니다. ',
    },
    {
      question: '에테르 필요 합니까? 그것은 다른 cryptocurrencies를 지원 합니까?',
      answer: '네입니다. 닌자만 지금, ETH를 수락 하지만 지원 다른 통화에 대 한 곧 추가 될 것 이다.',
    },
    {
      question: '닌자 어떻게 시작 합니까?',
      isList: true,
      answer: [
        {
          title: '에테르를 얻을:',
          content: '귀하의 신용 카드 또는 Coinbase 또는 Binance 같은 인기 있는 동전 교환에 직접 PEX에에서 ETH를 구입할 수 있습니다.',
        },
        {
          title: 'PEX 지갑 가기:',
          content: 'PEX 지갑에는 ETH를 전송 합니다. PEX 지갑은 완전히 분산, 귀하의 휴대 전화에 개인 키를 개최만 전송할 수 있고 ETH를 받을.',
        },
        {
          title: '배 팅:',
          content: '선택 하 고 내기 (즉 브라질-스페인), 결과 (즉, 브라질 승) 사이트 (예: 지원 또는 결과 대 한 내기) 시장\n' +
          '내기 (즉 1 ETH)와 확률을 원하는 스테이크를 입력 (예: 1 / 2.25)\n' +
          'BEX 일치 엔진 다음 베팅 확률 설정에 대 한 다른 순서를 찾을 것입니다.',
        },
        {
          title: '보고서에 대 한 대기:',
          content: '귀하의 계정에 귀하의 위 닝 에스크로 스마트 계약에서 자동으로 전송 됩니다 만약 당신이 이기 면.',
        },
      ],
    },
    {
      question: '내 자신의 선호 확률 설정 합니까? 어떻게?',
      answer: '예! 당신의 자신의 내기를 만들 때 당신은 당신이에 흥미 있는 이벤트와 결과에 내기를 입력 합니다. 다음, 단순히 귀하의 지분 및 원하는 확률 입력 합니다. 다음 PEX 엔진 자동으로 발견 하 고 누구는 동일한 이벤트에 관심을가지고 누가 수락 확률이와 일치.',
    },
    {
      question: '어떻게 불미스러운/불법 베팅을 경찰 당신은?',
      answer: '우리는 현재 견제와 균형 도조에 부적절 한 행동을 플래그의 시스템 구축.',
    },
    {
      question: '어떻게 시스템은 사람들 사이 내기의 결과 알고 있습니까? 누가 중재자 역할을 하며 다른 계약의 결론에 대 한 결과 확인 합니까?',
      answer: '닌자 곧 결과 확인 하 고 진실을 말하고 (DAO 기자!)를 incentivizing에 대 한 완전히 분산된 솔루션이 있을 것 이다. 로 우리가 FIFA 월드컵 시간에 맞춰 실행 됩니다, 반면에, 우리 팀 공개 소스 (livescore.com)를 사용 하 여 고 기자 역할.',
    },
    {
      question: '어디 동전에 개최?',
      answer: '아무도 자금을 보유 하고있다. 해상도이 때까지 모든 자금 에스크로에 안전 하 게 보관 됩니다.',
    },
    {
      question: '왜 내가 전통적인 방법을 사용 하 여 대신 blockchain 내기를 한다?',
      answer: '분산된 예측 exchange는 직접 사람과, 자신의 확율 및 내기를 만들 자유 100% 닌자 익명을 제공 하 고 지급을 보장을 제공할 것입니다. ',
    },
    {
      question: '방법에 대 한 개인 정보 보호 및 익명?',
      answer: '닌자는 다운로드, 그리고 아무 사인 ups 필요합니다. 아니 암호, 아니 전화 번호 및 아무 이메일 의미합니다. 100%의 익명',
    },
    {
      question: '모든 비용을 지불 해야 합니까?',
      answer: '수수료의 두 가지 주요 유형이 있다: (대 한 내기를 만드는 닌자) 작성자 비용과 네트워크 수수료 (플랫폼을 유지 하는 쪽으로는 창조 자 수수료의 비율).',
    },
    {
      question: '무엇을 할 때 결과 확정 해야 합니까?',
      answer: '아무것도입니다. 당신이 이길 경우 귀하의 계정에 귀하의 위 닝을 자동으로 전송 됩니다. 당신이 진다면, 그것은 다른 사람의 계정 것입니다.',
    },
    {
      question: '어디에 내기 하는 일치를 찾을 수 있습니까?',
      answer: '홈페이지에서 진행 중인 베팅 및 시장 수 있습니다. 어떤 당신이 좋아하는 찾을 수 없는 경우 직접 만들!',
    },
    {
      question: '스포츠, 이외 다른 것에 내기 수 있습니다? 그것은 어떻게 작동 합니까?',
      answer: '아주 빨리, 닌자는 태양 아래 모든 것에 적용 됩니다. 유일한 제한은 당신의 창의력을 될 것입니다. 쉽게 모든 미래의 이벤트에 어떤 시장 든 지를 만들고, 그것에 게 스포츠를 수, 정치, 과학, 시장, 기후... 당신은 그것을 이름. ',
    },
    {
      question: '일어나 악수 모바일 애플 리 케이 션에 게 무슨 일이?',
      answer: '우리 것 이다 수 통합 악수 (와 같은 약속, 계약 업로드, 등 평소 좋아하는 기능) 닌자 모바일 웹사이트에. ',
    },
  ],

  // MobileOrTablet components
  MOT_TITLE: '아무것도의 익명 교환"입니다',
  MOT_CONTENT_0: '닌자 네트워크는 액세스할 수 모바일을 통해',
  MOT_CONTENT_1: '익명 항목을 얻을 귀하의 모바일 브라우저에서',
  MOT_CONTENT_2: '를 엽니다.',
  MOT_CONTENT_3: '필요 없습니다 다운로드 합니다. 흔적이 필요합니다.',
  MOT_LIST_CONTENT: [
    {
      mainContent: '기술',
      placeHolderLink: '백서',
      link: 'https://medium.com/@ninjadotorg/shakeninja-bex-1c938f18b3e8',
      isBlankTarget: true,
      mainContent1: '보기',
    },
    {
      mainContent: '우리는 당신의',
      placeHolderLink: '질문',
      mainContent1: '에 대답',
      link: '/faq',
    },
    {
      mainContent: '',
      placeHolderLink: '전보',
      mainContent1: '에 미꾸라지를 가입',
      link: 'https://t.me/ninja_org',
      isBlankTarget: true,
    },
  ],

  /*
  *
  * White Paper
  *
  * ******************************************************************************************* */
  WHITE_PAPER_H1: '테리에 익명 피어-투-피어 예측 교환',
  WHITE_PAPER_SUBTITLE_1: '안녕하세요! 우리는 큰 괴 조, Bakunawa, Hakawai 및 Grootslang 닌자 팀 에서입니다. 우리는 blockchain에 전자 예측 교환 건물. 여기는 왜 우리가, 그리고 어떻게 그것은 작동!',
  WHITE_PAPER_SUBTITLE_2: '대화에 참여',
  WHITE_PAPER_INTRO: '소개',
  WHITE_PAPER_INTRO_1: '온라인 도박은 신뢰할 수 있는 제 3 자 제공 bookmakers에 의해 거의 독점적으로 실행 됩니다. 일반적으로 경우 처럼, 사용자가이 "신뢰할 수 있는 중앙 집중식된 30 파티 문제"에서 고통:',
  WHITE_PAPER_INTRO_2: [
    'Bookmakers 설정 (그들은 항상 승리) 그들은 항상 부탁 확률',
    'Bookmakers 무거운 5% 수 - 모든 내기에 30%의 마진',
    '내기는 돌이킬 수, 그리고 위 닝 확실 하지 않은',
    '완전히 익명 불가능',
    '사기는 피할 수 없는, 및 이렇게 것에 대 한 허용',
    '단일 오류 지점 - 만약 도박 사라진다?',
    '내기 도박으로 간주 됩니다 - 중앙된 파티 때문에 주로 편중 위험\'투명도의 부족',
  ],
  WHITE_PAPER_INTRO_3: '이 문제는 때 그래서 그것은 약간 사용자는 두 가지 폐 단의 낮은 하고있다 점점 궁금해 오프 라인 도박에 오면 10 곱합니다.',
  WHITE_PAPER_INTRO_4_HIGH_LIGHT: '솔루션: 어디에서 어떤 양쪽 익명 허용 암호화 증거 꺼 신뢰를 대체 하는 전자 예측 시스템 신뢰할 수 있는 제 3 자에 대 한 필요 없이 서로 대해 직접 내기 세계에서.',
  WHITE_PAPER_INTRO_5: '익명 피어-투-피어 전자 예측 교환 (PEX) 당사자는 중앙 기관 또는 도박을 거치지 않고 직접 서로 대 한 내기 수 있습니다. 베팅의 관리 및 위 닝의 정착은 총칭 의해 수행 실패의 모든 단일 지점에서 사용자를 보호 하는 blockchain 네트워크. PEX는 흥미로운 사용 사례, 전통적인 도박 메커니즘에서 이전 불가능 있도록 고유한 속성이 있습니다.',
  WHITE_PAPER_INTRO_6: '그것은 우리의 희망 PEX의 오늘날의 인식을 바꿀 것입니다 - 종종 불필요 하 게 묘사 그늘진 도박 게임으로 인해 주로 중앙된 당 이익을 만드는 비 윤리적인, 치열 한 방법을 찾고에 대 한 의존도를.',
  WHITE_PAPER_INTRO_7_HIGH_LIGHT: 'PEX 직접 오픈, 투명 한 예측 시장 교류와 그림자 도박 산업 도전. ',
  WHITE_PAPER_INTRO_8: '이 exchange와 사람들이 함께 얻이 됩니다 처럼 그들은 항상 할 스포츠, 정치, 과학, 시장, 기후, 및 태양 아래 모든 미래의 이벤트를 예측합니다 - 누가 세계에 투자 한 개인으로 서 우리는 자연스럽 게 할 구축',
  WHITE_PAPER_PEX: 'PEX는 무엇입니까?',
  WHITE_PAPER_PEX_1: '테리 blockchain에 위에 실행 하는, PEX 누구나 간단한 방법을 제공 합니다 익명 피어-투-피어 분산된 예측 교환입니다.',
  WHITE_PAPER_PEX_2: [
    '결과에는 지원 순서 (Ask) 또는 대 한 주문 (입찰)를 배치',
    '누워 확률) 마켓 메이커 또는 시장 즐긴다 (다시 확률)',
    '그들의 자신의 예측 시장 의 창조 자 ',
    '위 닝을 수집 즉시 ( 스마트 계약보장)',
  ],
  WHITE_PAPER_PEX_3: '합니다.',
  WHITE_PAPER_OUTCOME: '매매 할 수 있는 자산으로의 결과 가격으로 확률입니다.',
  WHITE_PAPER_OUTCOME_1: '증권 거래소에 tradeable 자산 공유, 이며 상인 (예: 판매 100 주 애플의 각 200 달러)를 공유 하는 단위 가격 에 내기.',
  WHITE_PAPER_OUTCOME_2: '동전 교환, tradeable 자산 동전, 그리고 상인 내기 동전 단위 가격 (예: 구매 2 Bitcoin 7000 달러에서).',
  WHITE_PAPER_OUTCOME_3: '마찬가지로, PEX 같은 분산된 예측 교환 , tradeable 자산 이벤트의 결과이며 상인 그 결과의 확율에 내기. 그들은 결과 대 한 있을 수 있습니다 (지원), 또는 그것에 대하여 내기. 예를 들어: 브라질 대 스페인은 "브라질 승" 될 수 있는 일치의 결과. 존은 2.0의 확률으로 그 결과에 내기 수 있습니다. 메리는 2 월 25 일의 확률으로 그 결과에 내기 수 있습니다. 피터는 1.9의 확률으로 그 결과 ("브라질" 잃거나 "브라질 무")에 대 한 있을 수 있습니다.',
  WHITE_PAPER_OUTCOME_4: 'A different type of exchange.',
  WHITE_PAPER_COMPARE: 'PEX 전통적인 도박 대',
  WHITE_PAPER_COMPARE_1: '중요 한 것은, PEX 말뚝을 누르고 베팅을 허용 하지 않습니다, 대신 결과 대 한 사용자와 결과 지 원하는 사용자를 찾습니다. 말뚝은 에스크로 스마트 계약에서 개최 됩니다.',
  WHITE_PAPER_COMPARE_2: 'The 에스크로 스마트 계약은 거침 없는 입니다. 그것은 정확 하 게 프로그램 실행 - 에스크로 균형 끝에 승자를 전달 하도록 - 의 가동, 사기 또는 제 3 자 간섭 가능성 없이. 양 당사자는 내기에 커밋, 일단 그것은 되돌릴 수입니다. 결제는 보장 인스턴트.',
  WHITE_PAPER_COMPARE_3: '전체 프로세스는 그들의 정체성을 드러내는 당사자 없이발생합니다. 100% 익명입니다.',
  WHITE_PAPER_COMPARE_4: '이 모든 중앙 기관 또는 마 권 없이발생합니다. 그것은 공동으로 밖으로 blockchain의 모든 노드에서 수행 됩니다.',
  WHITE_PAPER_COMPARE_5: 'This is why you should bet on the blockchain.',
  WHITE_PAPER_PEX_WORK: 'PEX는 어떻게 작동 합니까?',
  WHITE_PAPER_PEX_WORK_SUB_TITLE: 'PEX는 당신이 알고 다릅니다. 그것은 또한 당신이 무엇을 알고 보다 더 많은 자율성을 제공 합니다. 마찬가지로 중요 한 것은, 그것은 쉽게 내기 시장 및 장소 내기 순서를 만들 수 있도록.',
  WHITE_PAPER_STEP_1: '1 단계: 가져오기 에테르',
  WHITE_PAPER_STEP_1_1: '없는 경우 ETH 아직, 당신은 ETH PEX 귀하의 신용 카드에서 직접 구매의 선택이 있다. 또한 Coinbase 또는 Binance 같은 인기 있는 동전 교환 ETH를 구입할 수 있습니다.',
  WHITE_PAPER_STEP_1_2: 'PEX는 곧 다른 cryptocurrencies를 지원 합니다.',
  WHITE_PAPER_STEP_1_3: '쉽게 구매 ETH에-애플 리 케이 션.',
  WHITE_PAPER_STEP_2: '2 단계: 위에 PEX 지갑',
  WHITE_PAPER_STEP_2_1: '당신이 당신의 ETH와 베팅을 시작할 수 있도록 당신이 방금 PEX 지갑으로 구입 하는 ETH를 전송 합니다. PEX 지갑은 완전히 분산 이다. 귀하의 휴대 전화에 개인 키를 개최 하 고만 액세스할 수 있습니다. 만 전송 하 고 조교를 받을 수 있습니다.',
  WHITE_PAPER_STEP_2_2: '깔끔하게 조직된 PEX 지갑입니다.',
  WHITE_PAPER_STEP_3: '3 단계: 배 팅',
  WHITE_PAPER_STEP_3_1: '첫째, 예측 시장 관심을 선택 (즉, 브라질 - 스페인), 결과 (즉 \'브라질 승") 측면 (예: 지원 또는 대 한 내기는 결과).',
  WHITE_PAPER_STEP_3_2: '다음 입력 하려는 지분 내기 (즉 1 ETH)와 확률 (즉, 1/2 월 25 일). 스테이크는 에스크로 스마트 계약에 놓일 것 이다. PEX 일치 엔진 다음 베팅 확률 설정에 대 한 다른 순서를 찾을 것입니다.',
  WHITE_PAPER_STEP_3_3: '그거에요.',
  WHITE_PAPER_STEP_3_4: '우리의 조교가 한 아르헨티나에 있다.',
  WHITE_PAPER_STEP_4: '보고서에 대 한 4 단계: 대기',
  WHITE_PAPER_STEP_4_1: '일단 이벤트 끝 시장의 기자 보고 창 (시장 창조 자에 의해 설정 됨) 내에서 결과 보고 합니다. 일반적으로, 당신은 몇 분 안에 보고서를 기대 한다. 당신이 이길 경우 귀하의 위 닝 자동으로 전송 됩니다 에스크로 스마트 계약에서 귀하의 계정에.',
  WHITE_PAPER_STEP_4_2: 'May the odds be ever in your favour.',
  WHITE_PAPER_CREATE: '만들기 자신의 예측 시장',
  WHITE_PAPER_CREATE_1: '대부분의 사용자가 기존 시장에 주문을 것입니다 PEX 누구나 모든 미래의 이벤트에 대 한 예측 시장 만들 수 있습니다 - 스포츠, 정치, 과학, 또는 그대로의 다른 측면 현대 생활에서. 으로 시장 작성자, 시장 요금, 시장 마감 시간, 결과의 기자, 그리고 보고 설정할 수 있습니다 마감.',
  WHITE_PAPER_ARCHITECTURE: 'PEX 아키텍처',
  WHITE_PAPER_ARCHITECTURE_1: 'PEX 아키텍처의 핵심 구성 요소입니다.',
  WHITE_PAPER_ARCHITECTURE_2_HL: ' 예측 시장',
  WHITE_PAPER_ARCHITECTURE_2: 'PEX 누구나 모든 미래의 이벤트에 대 한 예측 시장 만들 수 있습니다. 이 모든 분야에서 수 - 스포츠, 정치, 과학, 라이프 스타일, 심지어 날씨 등등. 여기에 유일한 한계는 당신의 창의력. 각 시장에 체인 스마트 계약의 일부입니다. 그것은 그것의 자신의 순서 책, 제작자와 수취인.',
  WHITE_PAPER_ARCHITECTURE_3_HL: '주문도 서',
  WHITE_PAPER_ARCHITECTURE_3: '각 예측 시장 자체 주문도 서 있다. PEX 순서 책 모든 지원 결과 주문 (요청) 모든에 대 한 결과 순서 (입찰)을 관리합니다. 그것은 순서 책에 있는 항목에 동일한 가격 (확률)로 모든 순서를 집계합니다.',
  WHITE_PAPER_ARCHITECTURE_3_1: 'The order book.',
  WHITE_PAPER_ARCHITECTURE_4_HL: '일치 하는 엔진',
  WHITE_PAPER_ARCHITECTURE_4_1: 'PEX는 처음에 (선입 선출) 순서 책을 사용합니다. 주문은 가격-시간 우선 순위에서 실행 됩니다. 즉, 그것은 먼저, 가격에 의해 일치와 같은 가격으로 두 명령을 경우 다음 시간으로 일치 됩니다.',
  WHITE_PAPER_ARCHITECTURE_4_2: '경우에 따라 양쪽에 배치 하는 금액은, 그리고 순서를 부분적으로 채워질 것 이다. 나머지 순서 순서는 완전히 채워집니다 때까지 다음 최고의 가격-그-에 주문도 서와 일치 될 것입니다.',
  WHITE_PAPER_ARCHITECTURE_4_3: '당신의 완벽 한 일치입니다.',
  WHITE_PAPER_ARCHITECTURE_4_4: [
    '사용자 지원 결과 순서 오픈 순서 책에 배치',
    '다른 사용자 주문에 대 한 결과 오픈 순서 책에',
    '매칭 엔진 일치 하 고 두 주문 오픈 순서 책에 일치 하는 주문도 서에서 이동',
  ],
  WHITE_PAPER_ARCHITECTURE_5_HL: '나머지 API',
  WHITE_PAPER_ARCHITECTURE_5: 'PEX 나머지 API는 주문 관리, 계정 관리, 및 공공 시장 데이터에 대 한 끝점.',
  WHITE_PAPER_ARCHITECTURE_6_HL: '웹 소켓',
  WHITE_PAPER_ARCHITECTURE_6: 'PEX 웹 소켓 피드 주문 및 거래에 대 한 실시간 시장 데이터 업데이트를 제공합니다.',
  WHITE_PAPER_PRIVACY: '개인 정보 보호 및 익명',
  WHITE_PAPER_PRIVACY_SUB: '사용자에 게 제공 하는 개인 정보는 의도적으로 디자인.',
  WHITE_PAPER_PRIVACY_1_HL: '아니 다운로드',
  WHITE_PAPER_PRIVACY_1: 'PEX는 모바일 애플 리 케이 션 되지 않습니다. 그것은 모바일 웹에 자유롭게 액세스할 수입니다. 네이티브 모바일 애플 리 케이 션 때로는 더 나은 UI/UX를가지고, 그들은 안 드 로이드 플레이 스토어 또는 애플 앱 스토어와 같은 중앙 집중식된 응용 프로그램 저장소에서 호스트 되어야 합니다. 우리가 보기에 더 매력적인 UI 손상 된 개인 정보 보호에 대 한 허용 거래는 아니다.',
  WHITE_PAPER_PRIVACY_2_HL: '아니 사인 ups',
  WHITE_PAPER_PRIVACY_2_1: '비밀 번호, 이메일 또는 전화 번호에 대 한 필요는 사용 되지 않습니다. ',
  WHITE_PAPER_PRIVACY_2_2: 'PEX는 귀하의 개인 정보를 수집 하지 않습니다. 완벽 한 프라이버시와 PEX를 사용할 수 있습니다. PEX를 처음 열 때 공개/개인 키 쌍은 백그라운드에서 자동으로 생성 하 귀하의 휴대 전화에 로컬로 저장 합니다. 공개 키를 익명 사용자 이름으로 작동 하 고 개인 키가 암호. PEX는 개인 키에 액세스할 수 없는 - 만 당신이 할',
  WHITE_PAPER_PRIVACY_2_3: 'Note는 프로필 설정에 그들의 이메일 주소를 입력 하는 사용자에 대 한 옵션 제공. 목적은 되지 않습니다 귀하의 이메일을 수집 하지만 더 나은 경험을 위해 특히 사용 지불에 관련 된 경우. 그것은 완전히 선택 사항입니다.',
  WHITE_PAPER_PRIVACY_2_4: 'Note 설정에서 개인 키를 백업 하는 옵션은 또한. 이렇게 하는 것이 좋습니다.',
  WHITE_PAPER_PRIVACY_3_HL: '익명 예측',
  WHITE_PAPER_PRIVACY_3: 'PEX는 공공 blockchain, 테리 위에 구축 하지만 익명 공개 키를 유지 하 여 개인 정보 보호 유지 됩니다. 대 중 누군가가 뭔가에 예측 볼 수 있는, 하는 동안 누군가가 누구 인지 찾을 수 거의 불가능 하다 아니다.',
  WHITE_PAPER_PRIVACY_4_HL: '일치 하는 익명 순서',
  WHITE_PAPER_PRIVACY_4: '재고 및 동전 교환 마찬가지로 순서 책, 크기, 확률, 및 시간, 하지만 순서 책 주문 업체와 빼앗 고는 공개 하지 않습니다. 순서 책 기록 내기 익명 파티 이벤트의 반대 그들의 예측에 따라 서로 대 한 장소. 일단 이벤트 결론을 보고서는 사용할 수 있는 에스크로 자금 우승자에 게 자동으로 전송 됩니다.',
  WHITE_PAPER_FEE: '수수료',
  WHITE_PAPER_FEE_1: '수수료의 두 가지 주요 유형이 있다: 요금 및 네트워크 요금 승리.',
  WHITE_PAPER_FEE_2: '승리 수수료 는 그 시장 총 위 닝의 시장 창조 자에 의해 설정 됩니다. 그것은 전적으로 그들의 자신의 비용을 설정 하려면 시장 창조 자입니다. PEX 누구나 예측 시장 만들 수 있습니다, 이후 우리 수수료 시장 중 매우 경쟁력이 있을 것입니다 기대 합니다. 이것은 사용자를 위한 최상의 케이스 시나리오 이다.',
  WHITE_PAPER_FEE_3: '네트워크 수수료는 창조주의 승리 요금의 20%. 이 엔지니어링, 인프라 및 네트워크의 유지 보수에 대 한 지불합니다. 처음부터,이 코어 닌자 팀에 의해 수행 됩니다. 하지만 우리는 시간이 지남에 따라 우리 팀 분산 되며 전체 사회까지 열리는 메커니즘 디자인 기대 합니다.',
  WHITE_PAPER_FEE_4: '필요에 따라, 우리는 고려 추천 수수료 시장 창조주에 대 한. 추천 풀 10% 수 - 는 시장에 더 많은 사용자를 추가 하는 데 도움이 됩니다 승리 수수료의 20%.',
  WHITE_PAPER_SETTLEMENT: '정착',
  WHITE_PAPER_SETTLEMENT_1: '깊은 우리는 처음 속도 지방 분권, 항상 보안을 유지 하면서 사이의 타협을 공격 하는 것 같다 더 PEX, 건물 안으로 다이빙. 각 이벤트 (예: 스포츠 이벤트) 후 즉시 사용할 수 있도록 결과의 보고서를 요구 한다, 타협에 관하여 우리는 지금 속도, 선택할 것입니다.',
  WHITE_PAPER_SETTLEMENT_2: '첫 번째 릴리스에서 핵심 닌자 팀 가정 보고 역할 및 보고서 모든 이벤트의 결과. 우리는 연구 하 고 결과 보고 지역 사회 있도록 분산된 메커니즘 설계 있어.',
  WHITE_PAPER_SUMMARY: '요약',
  WHITE_PAPER_SUMMARY_1: 'PEX는 당사자는 중앙 기관 또는 도박을 거치지 않고 직접 서로 대해 내기 수 있도록 전자 예측의 순전히 피어-투-피어 버전입니다. ',
  WHITE_PAPER_SUMMARY_2: 'PEX는 오픈-소스, 그것의 디자인은, 아무도 소유 하 고 또는 컨트롤 PEX와 모든 부분을 걸릴 수 있습니다 ',
  WHITE_PAPER_SUMMARY_3: 'PEX는 오픈 소스에',
  WHITE_PAPER_SUMMARY_4: '빌드 PEX 우리와 함께입니다. 가입 대화',
  WHITE_PAPER_END: 'And it actually works',
  WHITE_PAPER_END_1: 'Hey, thanks for reading. Ninja will go live on the testnet on 5 June! We’re excited to hear your thoughts.',
};
