export default {
  HELLO: 'hello {name}',
  buy: 'Buy',
  sell: 'Sell',
  amount: 'amount',
  askUsingCreditCard: 'for {total} {fiatCurrency} using card?',
  change: 'Change',
  ccNumber: 'Number',
  ccExpire: 'Expiry',
  ccCVC: 'CVC',
  overCCLimit: 'You have reached your credit card limit! You have already used {currency}{amount} in the dojo today. ',

  required: 'Required',
  ccExpireTemplate: 'MM/YY',
  securityCode: '325',
  shakeNow: 'Shake',
  offerHandShakeContent: '{offerType} {amount} {currency} for {total} {currency_symbol} in {payment_method}?',
  offerHandShakeContentMe: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMe: '{offerType} {something} for {amount} {currency}',
  offerHandShakeContentMeDone: '{offerType} {amount} {currency} for {total} {currency_symbol} ({payment_method})',
  offerHandShakeExchangeContentMeDone: '{offerType} {something} for {amount} {currency}',
  instantOfferHandShakeContent: 'You{just}{offerType} {amount} {currency} for {total} {currency_symbol} on your card - fee {fee}%',
  offerDistanceContent: '{distance} away',
  transactonOfferInfo: 'Successful ({success}) / Failed ({failed})',
  createOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  handshakeOfferConfirm: 'You are about to {type} {amount} {currency} for {total} {currency_symbol}',
  rejectOfferConfirm: 'Do you want to Reject this handshake? You will not be able to make transactions for 4 hours.',
  completeOfferConfirm: 'Finish shaking?',
  withdrawOfferConfirm: 'Are you sure you want to withdraw?',
  cancelOfferConfirm: 'Cancel this order?',
  closeOfferConfirm: 'Finish your order?',
  acceptOfferConfirm: 'Accept the order?',
  createOfferSuccessMessage: 'Success! You have created an offer on Ninja.',
  shakeOfferSuccessMessage: 'Success! A ninja has shaked on your order.',
  closeOfferSuccessMessage: 'Success! Your order is now closed.',
  completeShakedfferSuccessMessage: 'You have successfully shaked on Ninja',
  cancelShakedfferSuccessMessage: 'You have cancelled your order ',
  withdrawShakedfferSuccessMessage: 'Your offer has been withdrawn.',
  buyUsingCreditCardSuccessMessge: 'Your order using your credit card has gone through.',
  notEnoughCoinInWallet: 'You don\'t have enough coin right now. Please top up your wallet.',

  createOfferStoreConfirm: 'Do you want to set up an offer to {intentMsg}?',
  notEnoughCoinInWalletStores: 'You don\'t have enough coin right now. Please top up your wallet.',
  addOfferItemSuccessMassage: 'Success! Your order is now listed on Ninja',
  deleteOfferItemSuccessMassage: 'You have successfully deleted your order.',
  shakeOfferItemSuccessMassage: 'You have successfully shaked on Ninja',
  acceptOfferItemSuccessMassage: 'Good news! Your order has been accepted.',
  cancelOfferItemSuccessMassage: 'Your order has been cancelled!',
  rejectOfferItemSuccessMassage: 'You rejected a fellow ninja\'s order.',
  completeOfferItemSuccessMassage: 'Good news! Your order has been completed.',
  offerStoresAlreadyCreated: 'Oops! You already created an order on Ninja.',
  offerStoreHandShakeContent: '{offerTypeBuy} {amountBuy} {currency} at {fiatAmountBuy} {fiatAmountCurrency}. {offerTypeSell} {amountSell} {currency} at {fiatAmountSell} {fiatAmountCurrency}',
  requireDefaultWalletOnMainNet: 'You must set your wallet on Mainnet',
  movingCoinToEscrow: 'Moving your coin to escrow. This may take a few minutes.',
  movingCoinFromEscrow: 'Moving your coin from escrow. This may take a few minutes.',
  'ex.create.label.amountBuy': 'I want to buy',
  'ex.create.label.amountSell': 'I want to sell',
  'ex.create.label.marketPrice': 'Current market price',
  'ex.create.label.premiumBuy': 'Your buying price',
  'ex.create.label.premiumSell': 'Your selling price',
  'ex.create.label.nameStation': 'Station name',
  'ex.create.label.phone': 'Phone',
  'ex.create.label.address': 'Meet-up place',
  'ex.create.label.exchangeRate': 'Exchange rate',
  'ex.create.label.stationInfo': 'Station information',

  'ex.createLocal.label.iWantTo': 'I want to',
  'ex.createLocal.placeholder.anyItem': 'any item or service',
  'ex.createLocal.label.coin': 'Coin',
  'ex.createLocal.label.amount': 'Amount',
  'ex.createLocal.label.phone': 'Phone',
  'ex.createLocal.label.address': 'Meet-up place',

  'ex.discover.label.priceBuy': 'BUY',
  'ex.discover.label.priceSell': 'SELL',
  'ex.discover.label.reviews': '({reviewCount})',
  'ex.discover.banner.text': 'Got coins? Turn them into a money-making machine.',
  'ex.discover.banner.btnText': 'BECOME A LOCAL EXCHANGE',
  'ex.discover.shakeDetail.label.amount': 'Amount',
  'ex.discover.shakeDetail.label.total': 'Total',
  'ex.discover.shakeDetail.label.maximum': 'Maximum:',
  'ex.me.label.with': 'With',
  'ex.me.label.from': 'From',
  'ex.me.label.about': 'About',
  'ex.btn.confirm': 'Confirm',
  'ex.btn.OK': 'OK',
  'ex.btn.notNow': 'Not now',

  'ex.label.buy': 'Buy',
  'ex.label.sell': 'Sell',
  'ex.label.bought': 'Bought',
  'ex.label.sold': 'Sold',
  'ex.label.buying': 'Buying',
  'ex.label.selling': 'Selling',
  'ex.label.buyer': 'buyer',
  'ex.label.seller': 'seller',

  'ex.exchange.status.created': 'created',
  'ex.exchange.status.active': 'active',
  'ex.exchange.status.closing': 'closing',
  'ex.exchange.status.closed': 'closed',
  'ex.exchange.status.shaking': 'shaking',
  'ex.exchange.status.shake': 'shake',
  'ex.exchange.status.completing': 'completing',
  'ex.exchange.status.completed': 'completed',
  'ex.exchange.status.withdrawing': 'withdrawing',
  'ex.exchange.status.withdraw': 'withdraw',
  'ex.exchange.status.rejecting': 'rejecting',
  'ex.exchange.status.rejected': 'rejected',

  'ex.cc.status.processing': 'Processing',
  'ex.cc.status.success': 'Done',
  'ex.cc.status.cancelled': 'Failed',

  'ex.shop.status.created': 'Verifying...',
  'ex.shop.status.active': 'Active',
  'ex.shop.status.closing': 'Pending...',
  'ex.shop.status.closed': 'Closed',

  'ex.shop.shake.status.pre_shaking': 'Shake pending',
  'ex.shop.shake.status.pre_shake': 'Shook',
  'ex.shop.shake.status.shaking': 'Shake pending...',
  'ex.shop.shake.status.shake': 'Shook',
  'ex.shop.shake.status.rejecting': 'Rejecting',
  'ex.shop.shake.status.rejected': 'Rejected',
  'ex.shop.shake.status.completing': 'Completing...',
  'ex.shop.shake.status.completed': 'Done',
  'ex.shop.shake.status.cancelling': 'Cancelling',
  'ex.shop.shake.status.cancelled': 'Cancelled',

  'ex.error.systemError': 'Sorry Ninja. Something went wrong. Come back soon.',
  'ex.error.312': 'Oh no! You cancelled your offer. You will not be able to make orders for 4 hours. Sorry',
  'ex.error.313': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.314': 'Looks like that listing has been deleted.',
  'ex.error.315': 'Sorry ninja, someone else got there first.',
  'ex.error.1': 'Oops! Something went wrong. Come back soon.',
  'ex.error.3': 'It looks like that token is invalid.',
  'ex.error.301': 'You are already a ninja.',
  'ex.error.302': 'Sorry, that ninja does not exist.',
  'ex.error.303': 'It looks like you have reached your credit card limit.',
  'ex.error.309': 'You already have a listing! To change your rates, please cancel your current listing.',
  'ex.error.default': 'Oops! Something went wrong.',

  'error.required': 'Required',
  'error.requiredOne': 'You need to fill in one of these!',
  'error.greaterThan': 'Must be greater than {min}',
  'error.lessThan': 'Must be less than {max}',

  'btn.initiate': 'Initiate',
  'btn.shake': 'Shake',
  'btn.reject': 'Reject',
  'btn.complete': 'Complete',
  'btn.withdraw': 'Withdraw',
  'btn.cancel': 'Cancel',
  'btn.close': 'Close',
  'btn.accept': 'Accept',

  // FAQ
  FAQ_TITLE: 'Вопросы и ответы',
  FAQ_HEADER_YELLOW: '',
  FAQ_HEADER: 'Децентрализованные предсказание обмен',
  FAQ_DATA: [
    {
      question: 'что такое PEX ниндзя?',
      answer: 'Ниндзя представляет собой обмен анонимный peer-to-peer децентрализованных предсказание, запущенное поверх Эфириума blockchain.',
    },
    {
      question: 'что особенного PEX? Почему следует поставить на один?',
      answer: 'Она позволяет сторонам ставить непосредственно против друг друга без прохождения через Центральный орган или букмекер. Это делает его 100% анонимный, никаких признаков вверх загружаемые файлы не требуется. Управление ставок и урегулирования выигрыши осуществляется коллективно blockchain сети, защищая пользователей от любой единой точки отказа. Можно также создать свои собственные рынки предсказаний. ',
    },
    {
      question: 'нужна ли мне эфира? Он поддерживает другие cryptocurrencies?',
      answer: 'Да. Ниндзя принимает только ETH для теперь, но очень скоро для других валют будет добавлена поддержка.',
    },
    {
      question: 'как начать с ниндзя?',
      isList: true,
      answer: [
        {
          title: 'Получите эфира:',
          content: 'Вы можете либо купить ETH непосредственно в PEX с вашей кредитной карты или из популярных монет обменов как Coinbase или Binance.',
        },
        {
          title: 'Пополните кошелек PEX:',
          content: 'Перенесите ETH в бумажник PEX. PEX кошелек полностью децентрализованной, закрытый ключ проводится на вашем телефоне, только вы можете передавать и получать ETH.',
        },
        {
          title: 'Сделайте ставку:',
          content: 'Выбор рынка, вы хотите ставку (т.е. Бразилия - Испания), результаты (т.е. победы Бразилии) и сайта (т.е. поддержки или ставку против результатов)\n' +
          'Введите ставку, вы хотите ставку (т.е. 1 ETH) и шансы (т.е. 1 / 2.25)\n' +
          'BEX соответствия будут затем найти другой порядок, что ставки против коэффициенты, заданные.',
        },
        {
          title: 'Ждать для отчета:',
          content: 'Если вы выиграете, ваши выигрыши будут автоматически переведены из смарт-контракт сделки на ваш счет.',
        },
      ],
    },
    {
      question: 'можно ли установить мой собственный предпочтительным шансы? Как?',
      answer: 'Да! При создании собственных ставку, вы войдете, событие, которое вы заинтересованы в и результаты, которые вы хотите сделать ставку на. Просто введите вашу ставку и шансы, что вы хотите. Затем обработчик PEX автоматически найдет и матч вы с кем-либо, имеет интерес в то же событие, и кто принимает ваши шансы.',
    },
    {
      question: 'как вы полиции непривлекательный/незаконный ставки?',
      answer: 'В настоящее время мы строим систему сдержек и противовесов для флага за неподобающее поведение в додзё.',
    },
    {
      question: 'как система знать результат ставки между людьми? ВОЗ выступает в качестве арбитра и проверяет один результат против другой на заключение контракта?',
      answer: 'Ниндзя скоро будет полностью децентрализованное решение для проверки результатов и стимулированием правду говорю (DAO Репортеры!). В то же время как мы будем запускать как раз вовремя для чемпионата мира по футболу, наша команда будет использовать общественный источник (livescore.com) и действовать в качестве репортера.',
    },
    {
      question: 'где проходит монеты?',
      answer: 'Никто держит средства. Все средства хранятся безопасной в эскроу, пока не будет достигнуто решение.',
    }, {
      question: 'Почему следует поставить на blockchain вместо использования традиционных методов?',
      answer: 'Децентрализованные предсказание обмен обеспечит вам свободу создавать собственные шансы и ставки непосредственно с кем-либо, предлагаем вам ниндзя 100% анонимность и гарантированные выплаты. ',
    }, {
      question: 'как насчет конфиденциальности и анонимности?',
      answer: 'Ниндзя требует никаких Скачиваний и не подписать взлеты. Это означает, что никакие пароли, без номера телефонов и без писем. 100% анонимность.',
    }, {
      question: 'нужно ли мне платить?',
      answer: 'Существует два основных типа сборов: создатель сборы (для ниндзя, который создает ставку) и сетевой платы (в процентах от создателя плату, которая идет на поддержание платформы).',
    }, {
      question: 'что нужно делать, когда завершается результат?',
      answer: 'Ничего. Если вы выиграете, ваши выигрыши будут автоматически переведены на ваш счет. Если вы потеряете, он будет кто-то чужой учетной записью.',
    }, {
      question: 'где можно найти ставки на матч?',
      answer: 'На домашней странице вы сможете просматривать текущие ставки и рынки. Если вы не можете найти любой понравившийся вам, создайте свой собственный!',
    }, {
      question: 'Помимо спорта можно ставить на что-нибудь еще? Как это работает?',
      answer: 'Очень скоро ниндзя будет применяться ко всем под солнцем. Единственное ограничение будет ваше творчество. Вы можете легко создать любой рынок на любых будущих событий, будь то спорт, политика, Наука, рынки, климат... вы назовите его',
    }, {
      question: 'то, что должно произойти для подтверждения мобильного приложения?',
      answer: 'Мы будет интеграция рукопожатие (и ваши любимые функции, такие как обещания, долговые расписки, загрузить контракт и т.д.) в ниндзя мобильный веб-сайт.',
    },
  ],

  // MobileOrTablet components
  MOT_TITLE: 'Анонимный обмен ничего',
  MOT_CONTENT_0: 'Ниндзя сеть доступна только через мобильный',
  MOT_CONTENT_1: 'Откройте',
  MOT_CONTENT_2: 'в вашем мобильном браузере, чтобы получить анонимный вход.',
  MOT_CONTENT_3: 'Не нужно загружать. Не Зарегистрируйся требуется.',
  MOT_LIST_CONTENT: [
    {
      mainContent: 'Читать',
      placeHolderLink: 'документ',
      link: 'https://medium.com/@ninjadotorg/shakeninja-bex-1c938f18b3e8',
      isBlankTarget: true,
    },
    {
      mainContent: 'Мы ответим на ваши',
      placeHolderLink: 'вопросы и ответы',
      link: '/faq',
    },
    {
      mainContent: 'Присоединяйтесь к dojo на',
      placeHolderLink: 'Телеграмма',
      link: 'https://t.me/ninja_org',
      isBlankTarget: true,
    },
  ],

  // landing page --> /coin-exchange
  COIN_EXCHANGE_LP_FAQ_TITLE: 'Есть вопросы?',
  COIN_EXCHANGE_LP_FAQ: [
    {
      question: 'Какая идентификация нужна для продавцов или покупателей?',
      answer: 'Нам не нужна проверка идентификации. Если вы подтвердите свой номер телефона, у вас будет шанс получить 1 бесплатный ETH, чтобы совершить транзакцию на Shake Ninja.',
    },
    {
      question: 'Принимаются ли кредитные карты?',
      answer: 'Да. Мы принимаем Visa, Mastercard, Amex и Discover.',
    },
    {
      question: 'Какие валюты принимаются для обмена?',
      answer: 'Мы принимаем все валюты.',
    },
    {
      question: 'Есть ли система отслеживания истории торговли?',
      answer: 'Да. Мы прослеживаем успешные и неудачные транзакции с четким отчетом для каждого продавца и покупателя.',
    },
    {
      question: 'Имеет ли какая либо страна ограничения по использованию платформы?',
      answer: 'Мы доступны для всех стран.',
    },
    {
      question: 'Есть ли децентрализованный обмен?',
      answer: 'Да, поэтому транзакция на 100% безопасна и надежна.',
    },
    {
      question: 'Могу ли я использовать Paypal?',
      answer: 'Мы не доступны в Paypal на данный момент.',
    },
    {
      question: 'Будут ли средства храниться в Эскроу?',
      answer: 'Да, либо на Эскроу или на смарт-контракте Эфириум Блокче́йн.',
    },
    {
      question: 'Как будет выполняться Смарт-договор, когда задействованы физические деньги и вероятны ли запоздания во время транзакций?',
      answer: 'Получив физическую наличность, продавец нажимает кнопку «принять», монета будет автоматически переведена покупателю. Процесс занимает от 10 до 20 минут.',
    },
  ],
  COIN_EXCHANGE_LP_TRADE_EASY_TRADE_SAFE: {
    title: 'Легкая и безопасная торговля',
    info: [
      {
        title: '1. Разместите вашу сделку',
        description: 'Выберите криптовалюту, которую вы хотите купить / продать по желаемой цене',
      },
      {
        title: '2. Выберите магазин',
        description: 'Найдите и выберите наиболее подходящий магазин в вашем регионе',
      },
      {
        title: '3. Выполните обмен',
        description: 'Отправьтесь в магазин и обменяйте наличные деньги на криптовалюту или криптовалюту на наличные деньги',
      },
      {
        title: '4. Подтвердите платеж',
        description: 'Процесс обезопасен на 100% за счет смарт-контракта',
      },
    ],
  },
  COIN_EXCHANGE_LP_START_TRADING_NOW: 'Начать торговать прямо сейчас',
  COIN_EXCHANGE_LP_PLACEHOLDER_INPUT: 'Ваша электронная почта',
  COIN_EXCHANGE_LP_TITLE_SUBMIT_BT: 'Присоединиться к списку рассылки',
  COIN_EXCHANGE_LP_SECOND_BOX_TITLE: 'Мы первые, кто предложил полностью децентрализованную платформу для покупки и продажи Bitcoin и Ethereum.',
  COIN_EXCHANGE_LP_SECOND_BOX_DESCRIPTION_1: 'Несколько способов оплаты: кредитная карта и наличные деньги',
  COIN_EXCHANGE_LP_SECOND_BOX_DESCRIPTION_2: 'Обеспеченная сделка по blockchain технологии',
  COIN_EXCHANGE_LP_SECOND_BOX_DESCRIPTION_3: '-Быстрое и удобное использование.',
  COIN_EXCHANGE_LP_THIRD_BOX_1: {
    title: 'Несколько способов оплаты',
    description: 'Мы обеспечиваем торговлю наличных денег на криптовалюту и кредитной карты на криптовалюту. Найдите своих ближайших трейдеров, не оставляя истории транзакций для каких-либо действий на нашей платформе.',
  },
  COIN_EXCHANGE_LP_THIRD_BOX_2: {
    title: 'Быстро и на ходу',
    description: 'Благодаря торговле на основе местоположения, мы позволяем вам совершать платежи за несколько минут с повышенным удобством.',
  },
  COIN_EXCHANGE_LP_THIRD_BOX_3: {
    title: '100% безопасно и надежно для обеих сторон',
    description: 'В отличие от любой другой платформы, мы не владеем ключами пользователей и предоставляем полный контроль ключами покупателям и продавцам.',
  },
};
