import { HANDSHAKE_API } from '@/config';
import { createAPI } from '@/reducers/action';

export const DISCOVER_ACTIONS = {
  LOAD_DISCOVER: 'LOAD_DISCOVER',
  LOAD_DISCOVER_SUCCESS: 'LOAD_DISCOVER_SUCCESS',
  LOAD_DISCOVER_FAILED: 'LOAD_DISCOVER_FAILED',

  INIT_HANDSHAKE: 'INIT_HANDSHAKE',
  INIT_HANDSHAKE_SUCCESS: 'INIT_HANDSHAKE_SUCCESS',
  INIT_HANDSHAKE_FAILED: 'INIT_HANDSHAKE_FAILED'
};

export const load = createAPI({
  API: HANDSHAKE_API.HANDSHAKE.LOAD,
  INIT: DISCOVER_ACTIONS.LOAD_DISCOVER,
  SUCCESS: DISCOVER_ACTIONS.LOAD_DISCOVER_SUCCESS,
  FAILED: DISCOVER_ACTIONS.LOAD_DISCOVER_FAILED,
});
export const init = createAPI({
  API: HANDSHAKE_API.HANDSHAKE.INIT,
  // INIT: ACTIONS.LOAD_DISCOVER,
  // SUCCESS: ACTIONS.LOAD_DISCOVER_SUCCESS,
  // FAILED: ACTIONS.LOAD_DISCOVER_FAILED,
});
