export const AUTH_ACTIONS = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',

  SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',

  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
};

import { HANDSHAKE_API } from '@/config';
import { createAPI } from '@/reducers/action';

// export const signIn = createAPI({
//   API: CAPITAL_API.BUSINESS.SIGN_IN,
//   INIT: AUTH_ACTIONS.SIGN_IN,
//   SUCCESS: AUTH_ACTIONS.SIGN_IN_SUCCESS,
//   FAILED: AUTH_ACTIONS.SIGN_IN_FAILED,
// });

// export const signUp = createAPI({
//   API: CAPITAL_API.BUSINESS.SIGN_UP,
//   INIT: AUTH_ACTIONS.SIGN_UP,
//   SUCCESS: AUTH_ACTIONS.SIGN_UP_SUCCESS,
//   FAILED: AUTH_ACTIONS.SIGN_UP_FAILED,
// });

// export function signOut(kind) {
//   return { type: AUTH_ACTIONS.SIGN_OUT_SUCCESS, kind };
// };
